language: python
python:
  -  "2.7"
services:
  - docker
install:
  -  make deps
script:
  -  make lint
  -  make test
  -  make docker_build
  -  make docker_push
deploy:
  provider: heroku
  app: se_hello_printer_app
  api_key: ${HEROKU_API_KEY}  
